### ISSUE TITLE
Search name in all languages

### ISSUE THREAD

**Issue by nichtich** [EvaSeidlmayer/orcid-for-wikidata#2]
The SPARQL `SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en"}` might only catch English names.

**Comment by EvaSeidlmayer** [comment]
all these language statements are requested by the SPARQL-queries now:
SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE], ar,be,bg,bn,ca,cs,da,de,el,en,es,et,fa,fi, fr,he,hi,hu,hy,id,it,ja,jv,ko,nb,nl,eo,pa,pl,pt,ro,ru,sh,sk,sr,sv,sw,te,th,tr,uk,yue,vec,vi,zh"}
