### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by Daniel-Mietchen** [EvaSeidlmayer/orcid-for-wikidata#4]
to clarify reusability.

**Comment by Daniel-Mietchen** [comment]
Just noticed that the README states, at the very end, 

> All source code licensed under [ISC license](https://www.isc.org/licenses/)

That is sufficient to clarify reusability in most cases, but the absence of a dedicated license file essentially excludes the repo from things like search by license.

**Comment by EvaSeidlmayer** [comment]
Thank you Daniel! I added a license.
